type Calculation {
  result: Float!
}

type Product {
  id: Int
  name: String!
  description: String
  type: Type!
  created_at: String
}

input createProductInput {
  name: String!
  description: String
  type: Type
}

input createWarehouseInput {
  name: String!
  capacity: Int!
  type: Type!
}

type SumProductWarehouseHistory {
  product_name: String!
  sum: Int
}

enum Type {
  hazardous
  nonhazardous
}

type Warehouse {
  id: Int
  name: String!
  capacity: Int!
  availableCapacity: Int
  type: Type!
  products: [SumProductWarehouseHistory]
  created_at: String
}

input createWarehouseHistoryInput {
  warehouse_id: Int!
  product_id: Int!
  quantity: Int!
}

enum WarehouseHistoryType {
  import
  export
}

type WarehouseHistory {
  id: Int
  warehouse_id: Int!
  product_id: Int!
  product_name: String!
  product_description: String!
  product_quantity: Int!
  type: WarehouseHistoryType!
  created_at: String
}

type Query {
  products: [Product]
  warehouses: [Warehouse]
  product(id: Int!): Product
  warehouse(id: Int!): Warehouse
  warehouseHistory(id: Int!): [WarehouseHistory]
}

type Mutation {
  sum(num1: Int!, num2: Int!): Calculation
  subtract(num1: Int!, num2: Int!): Calculation
  multiply(num1: Int!, num2: Int!): Calculation
  divide(num1: Int!, num2: Int!): Calculation
  sumArray(digits: [Int]): Calculation
  createProduct(product: createProductInput!): Product
  deleteProduct(id: Int!): String
  createWarehouse(warehouse: createWarehouseInput!): Warehouse
  updateWarehouse(warehouse: createWarehouseInput!): Warehouse
  deleteWarehouse(id: Int!): String
  import(warehouseHistory: createWarehouseHistoryInput!): Int
  export(warehouse_id: Int!, product_name: String!, quantity: Int!): Int
}
